const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
const DESTROY_PRODUCT_SUCCESS = 'DESTROY_PRODUCT_SUCCESS';
const UNSET_FAVORITE_PRODUCT = 'UNSET_FAVORITE_PRODUCT';
const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export { LOAD_PRODUCTS_SUCCESS, DESTROY_PRODUCT_SUCCESS, UNSET_FAVORITE_PRODUCT, LOAD_USERS_SUCCESS }
